language: cpp
os:
- linux
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - george-edison55-precise-backports  # for cmake 3
    packages:
    - g++-4.8
    - clang-3.7
    - cmake
    - cmake-data
install:
- if [ "`echo $CXX`" == "g++" ]     && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=g++-4.8; fi
script:
- ./package.sh
before_deploy:
    - export RELEASE_FILE=$(bin.tar.gz)
    - ls
    - ls build
    - echo "Deploying $RELEASE_FILE to GitHub"
deploy:
  provider: releases
  api_key:
    secure: cb061a51e776f2fe17add85a0e0d55f20b0b54b9
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    repo: BWISE
    tags: true
